sudo: required
services:
  - docker

before_install:
  - docker build -t chavincc/client-test -f Dockerfile.dev .

script:
  - docker run -e CI=true chavincc/client-test npm run test

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_ACCESS_KEY'
  region: 'ap-southeast-1'
  app: 'react-client'
  env: 'ReactClient-env'
  bucket_name: 'elasticbeanstalk-ap-southeast-1-876733262264'
  bucket_path: 'react-client'
  on:
    branch: master
